name: BCI
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - pip
  - ipykernel
  - ipython
  - jupyter
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - seaborn
  - flask
  - sqlalchemy
  - pillow
  - requests
  - beautifulsoup4
  - lxml
  - pyyaml
  - cryptography
  - ffmpeg
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit
  - pip:
    - accelerate
    - addict
    - altair
    - annotated-types
    - ansi2html
    - antlr4-python3-runtime
    - appdirs
    - astor
    - bids
    - bids-validator
    - blinker
    - blis
    - braceexpand
    - braindecode
    - cachetools
    - catalogue
    - cfgv
    - click
    - cloudpathlib
    - confection
    - configargparse
    - contexttimer
    - contourpy
    - cycler
    - cymem
    - dash
    - dash-core-components
    - dash-html-components
    - dash-table
    - decorator
    - decord
    - diffusers
    - distlib
    - docker-pycreds
    - docopt
    - docstring-inheritance
    - easydict
    - einops
    - evdev
    - fairscale
    - filelock
    - fonttools
    - formulaic
    - fsspec
    - ftfy
    - gitdb
    - gitpython
    - greenlet
    - h5py
    - huggingface-hub
    - identify
    - imageio
    - imageio-ffmpeg
    - importlib-metadata
    - interface-meta
    - iopath
    - itsdangerous
    - joblib
    - kaggle
    - kiwisolver
    - langcodes
    - lazy-loader
    - llvmlite
    - markdown-it-py
    - matplotlib
    - mne
    - mne-bids
    - moviepy
    - murmurhash
    - nbformat
    - networkx
    - nib
